<!doctype html>
<html>
  <head>
    <title>Exceptions</title>
    <link rel="stylesheet" href="../../common.css">		
  </head>
  <body>
    <h1>Exceptions</h1>
	<p>When a program violates the semantic constraints, an error is signaled as an <i>exception</i>.</p>
	
	<h2>Kinds of Exceptions</h2>
	<ul><li><b>Checked exceptions</b>: Exceptions checked at <i>compile time</i>. They are Throwable classes (and its subclasses) other than unchecked exceptions. E.g. InputStream.read() throws IOException if an I/O error occurs.</li>
	<li><b>Unchecked exceptions</b>: Exceptions processed at <i>run time</i>. They are the RuntimeException and Error classes (and their subclasses). E.g. NullPointerException is thrown when an application attempts to use null in a case where an object is required.</li></ul>

	<h2>Execution of try-finally and try-catch-finally</h2>	
	<b>If the try block is executed, then the finally block is executed</b>
<ul><li>If the finally block completes, then the <i>try statement</i> completes</li>
<li>If the finally block returns S, then the <i>try statement</i> returns S</li></ul>

	<b>If the try block throws V</b>
<ul><li>If the V is assignable to the parameter of any catch clause, then the first (leftmost) such catch clause block is executed</li>
  <ul><li>If the catch block completes, then the finally block is executed</li>
    <ul><li>If the finally block completes, then the <i>try statement</i> completes</li></ul>
    <ul><li>If the finally block returns R, then the <i>try statement</i> returns R</li></ul></ul>
  <ul><li>If the catch block returns R, then the finally block is executed</li>
    <ul><li>If the finally block completes, then the <i>try statement</i> returns R</li></ul>
    <ul><li>If the finally block returns S, then the <i>try statement</i> returns S (and R is discarded)</li></ul></ul>
<li>If the V is not assignable to the parameter of any catch clause, then the finally block is executed</li>
  <ul><li>If the finally block completes, then the <i>try statement</i> throws V</li></ul>
  <ul><li>If the finally block returns S, then the <i>try statement</i> returns S (and V is discarded)</li></ul>
</ul>

	<b>If the try block returns R, then the finally block is executed</b>
<ul><li>If the finally block completes, then the <i>try statement</i> returns R</li>
<li>If the finally block returns S, then the <i>try statement</i> returns S (and R is discarded)</li>
<li>The return statement in the finally block discards unhandled exceptions. C# compiler gives error message (<i>CS0157</i>) for the return statement in the finally block</li>
</ul>


<p>An <i>abrupt completion</i> can be break, continue, return, throw and yield statements. The try statements can only have return and throw statements.</p>

<b>The finally Block</b>
<ul><li>The finally block always executes when the try block exits. This ensures that the finally block is executed even if an unexpected exception occurs</li>
<li>The finally block may not execute if the JVM exits (System.exit) or there is an infinite loop while the try or catch code is being executed</li>
<li>If thread is interrupted, then the finally block is still executed</li>
</ul>

	<div class="code"><code>	
<table width="100%">
  <tr>
    <td><pre>public static String concatString() {
    String str = new String();
    try {
    	str += "abc";
    	return str;
    } finally {
    	str += "cde";
    	System.out.println(str);
    }	
}

</pre></td>
    <td><pre>public static String concatStringDecompiled() { <i>// decompiled (simplifying StringBuilder().toString())</i>
    String str = new String(); <i>// String is immutable</i>
    try {
        str += "abc";
        String s = str; <i>// the return value is put on the stack</i>
        str += "cde";
        System.out.println(str);
        return s;
    } catch (Exception exception) {
        str += "cde";
        System.out.println(str);		
        throw exception;
    }	
}</pre></td>
  </tr>
</table>
</code></div>

    <table>
      <tr>
        <td><i>Output for String</i>:<br>
        abccde<br>
        abc</td>
        <td><i>Output for StringBuilder</i>:<br>
        abccde<br>
        abccde</td>
     </tr>
    </table>

<div class="code"><code><pre>public class Car {
   public String checkBattery() throws BatteryException {
       <i>// implementation</i>
   }
   public String checkFuel() throws FuelException {
       <i>// implementation</i>
   }
   public String start() {
       try {
           checkBattery();
           checkFuel();
       } catch (BatteryException be) {
           return "BadBattery";
       } finally {
           return "";
       }
   }
}</pre></code></div>
<i>Output</i>:<br>No matter how the code reaches the finally block, the start() method can only return an empty string. Any FuelException that might arise will simply be abandoned. 

    <h2>The try-with-resources Statement</h2>
	<p>A <i>resource</i> is an object that must be closed after the program is finished with it.
	<ul><li>Any object that implements <i>(java.io.Closeable extends) java.lang.AutoCloseable</i> interface, can be used as a resource</li>
	<li>Putting cleanup code in a finally block is always a good practice, even when no exceptions are anticipated</li>
	<li>The close methods of resources are called in the <i>opposite</i> order of their creation</li></ul>
	<div class="code"><code>	
<table width="100%">
  <tr>
    <td><pre>import java.io.*;
	
private static void copy(InputStream in, OutputStream out) throws IOException {
    byte[] buf = new byte[8192];
    int n;
    while ((n = in.read(buf)) > 0) {
        out.write(buf, 0, n);
    }
}

public static void copyJava6() throws Exception {
    File file = new File("example.txt");
    URI u = URI.create("http://www.example.com/");
    InputStream in = u.toURL().openStream();
    OutputStream out = new FileOutputStream(file);
    try {
        copy(in, out);
    } finally {
        out.close(); <i>// check IOException</i>
        if (in != null) {
            in.close();
        }
    }
}</pre></td>
        <td><pre>import java.nio.file.*;
		
public static void copyJava7() throws Exception {
    Path path = Paths.get("example.txt");
    URI u = URI.create("http://www.example.com/");
    try (InputStream in = u.toURL().openStream()) {
        Files.copy(in, path); <i>// check FileAlreadyExistsException</i>
    }
}</pre></td>
     </tr>
    </table>
	</code></div>

	<h2>Finalization of Class Instances</h2>
	<p>The class <i>Object</i> has a <i>protected</i> method called <i>finalize</i>; this method can be overridden by other classes. Before the storage for an object is reclaimed by the garbage collector, the Java Virtual Machine will invoke the <i>finalizer</i> of that object.</p>
<div class="code"><code><pre>@Override
protected void finalize() throws Throwable { 
    try {
        /* finalize object */
    } finally { 
        super.finalize(); 
    } 
}</pre></code></div>
	<h2>Java Language Specification</h2>
 	<ul>
	  <li><a href="https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.2">Execution of try-finally and try-catch-finally</a></li>
	  <li><a href="https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.1">Normal and Abrupt Completion of Statements</a></li>
	  <li><a href="https://blogs.oracle.com/post/java-quiz-try-catch-finally-exception">Quiz yourself: How does a Java finally block handle an exception?</a></li>	  
 	</ul>
	
  </body>
</html>